# Generated by Django 4.1.2 on 2022-11-26 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id_classroom', models.AutoField(auto_created = True,primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('abbrv', models.CharField(max_length=5)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('credits', models.IntegerField(default=5)),
                ('max_persons', models.IntegerField(default=100)),
                ('approved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('w', 'Winter'), ('s', 'Summer')], default='w', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('role', models.CharField(choices=[('a', 'administrator'), ('g', 'garant'), ('l', 'lektor'), ('v', 'visitor'), ('s', 'student')], default='v', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id_termin', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('repeted', models.BooleanField(default=False)),
                ('time_start', models.TimeField(default=None)),
                ('time_end', models.TimeField(default=None)),
                ('date', models.DateField(default=None)),
                ('weekday', models.CharField(default=None, max_length=10)),
                ('max_points', models.IntegerField(default=None)),
                ('description', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(choices=[('l', 'lecture'), ('c', 'cviceni'), ('z', 'exam'), ('p', 'project'), ('h', 'homework')], default='l', max_length=1)),
                ('id_classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='garant_id',
            field=models.ForeignKey(db_column='id_person', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.person'),
        ),
        migrations.CreateModel(
            name='User_Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('id_student', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
                ('id_termin', models.ForeignKey(db_column='id_termin', on_delete=django.db.models.deletion.DO_NOTHING, to='main.termin')),
            ],
            options={
                'unique_together': {('id_student', 'id_termin')},
            },
        ),
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('id_teacher', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
            ],
            options={
                'unique_together': {('id_teacher', 'id_course')},
            },
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('id_student', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
            ],
            options={
                'unique_together': {('id_student', 'id_course')},
            },
        ),
    ]
