# Generated by Django 4.1.3 on 2022-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='id_classroom',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termin',
            name='id_termin',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
