# Generated by Django 4.1.3 on 2022-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classrooms_id_classroom_alter_course_id_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='id_classroom',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termin',
            name='id_termin',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
