# Generated by Django 4.1.3 on 2022-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assign_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='termin',
            name='max_points',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='termin',
            name='repeted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termin',
            name='time_end',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='termin',
            name='time_start',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='termin',
            name='weekday',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
