# Generated by Django 4.1.3 on 2022-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_id_course_alter_termin_id_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='id_classroom',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
