# Generated by Django 4.1.3 on 2022-11-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_classrooms_id_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='id_student',
            field=models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='main.person'),
        ),
    ]
